dist: xenial

git:
  depth: 3

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    - LISP=ccl
    #- LISP=clisp
    #- LISP=ecl
    #- LISP=cmucl

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

matrix:
  allow_failures:
    - env: LISP=clisp
    #- env: LISP=ccl

install:
  - LISP_IMAGE=sbcl-2.0.5.core
  - if [ "$LISP" = "sbcl" ]; then wget https://gitlab.com/digikar99/lisp-images/-/raw/master/$LISP_IMAGE; fi
  - chmod +x $LISP_IMAGE
  - pwd
  - ls -l

script:
  # numcl from 2020-06-10 does not load in SBCL 2.0.5
  # (config-var pycmd) is set from .config file, in do-after-load.lisp
  - ./$LISP_IMAGE --eval \
           "(progn
              (in-package :cl-user)
              (push (uiop:getcwd) ql:*local-project-directories*)
              (ql:quickload \"py4cl2\")
              (ql:quickload \"py4cl2/tests\"))" \
     --eval "(progn
               (let ((report (py4cl2/tests:run)))
                 (when (or (plusp (slot-value report 'clunit::failed))
                           (plusp (slot-value report 'clunit::errors)))
                   (princ report)
                   (uiop:quit 1)))
               (unless (member :ecl *features*)
                 (ql:quickload \"py4cl2+numcl/tests\")
                 (let ((report (py4cl2/tests:run)))
                   (when (or (plusp (slot-value report 'clunit::failed))
                             (plusp (slot-value report 'clunit::errors)))
                     (princ report)
                     (uiop:quit 1))))
               (format t \"ALL TESTS RAN SUCCESSFULLY!\")
               (uiop:quit 0))"
    
notifications:
  email: false
