language: common-lisp
dist: xenial

git:
  depth: 3

env:
  matrix:
    - LISP=abcl
    - LISP=sbcl
    - LISP=ecl
    - LISP=ccl

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

install:
  - echo $PATH
  - java -version
  - which java
  - sudo apt install openjdk-8-jre
  - java -version
  - sudo rm /usr/local/lib/jvm/openjdk11/bin/java
  - which java
  - sudo update-alternatives --display java
  - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  # https://stackoverflow.com/questions/5735666/execute-bash-script-from-url
  - bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)
  - export EXOTIC_DIR="$HOME/(some exotic name')/"
  - export EXOTIC_DIR_PYTHON="$EXOTIC_DIR/python"
  - mkdir -p "$EXOTIC_DIR"
  - rsync -rR "$HOME/build/digikar99/py4cl2" "$EXOTIC_DIR"
  - ln -s "/usr/bin/python3" "$EXOTIC_DIR_PYTHON"
  - cd ~/
  - ls -l
  - ls "$EXOTIC_DIR"
  - nproc
  - pwd
  - python3 --version
  - /"$EXOTIC_DIR_PYTHON" --version

script:
  # Testing it on the second load confirms that functionalities do not
  # solely eval-when compile-toplevel, and that they persist across multiple loads.
  - cl --load "$EXOTIC_DIR/$HOME/build/digikar99/py4cl2/tests/travis-pre-test.lisp"
  - cl --load "$EXOTIC_DIR/$HOME/build/digikar99/py4cl2/tests/travis-test.lisp"

notifications:
  email: false
