language: lisp
sudo: required

git:
  depth: 3

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    - LISP=ccl
    #- LISP=clisp
    #- LISP=ecl

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=ccl

install:
  - ./install.sh
  #- curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash  
    
script:
  - cl -e "(ql:quickload :py4cl)
           (ql:quickload :py4cl-tests)

           (if (or
                 ;; Python 2
                 (let ((report (py4cl-tests:run)))
                   (when (or (plusp (slot-value report 'clunit::failed))
                             (plusp (slot-value report 'clunit::errors)))
                     (princ report)))

                 ;; Python 3
                 (let ((py4cl:*python-command* \"python3\"))
                   (let ((report (py4cl-tests:run)))
                     (when (or (plusp (slot-value report 'clunit::failed))
                               (plusp (slot-value report 'clunit::errors)))
                       (princ report)))))
                ;; If either run returned a report (i.e. failed), exit with error
                (uiop:quit 1))"
