language: common-lisp
dist: xenial

git:
  depth: 3

env:
  matrix:
    - LISP=abcl-bin
    - LISP=sbcl-bin
    - LISP=ecl
    - LISP=ccl-bin

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

install:
  - echo $PATH
  - ls /usr/local/lib/jvm/
  - sudo rm -rf /usr/local/lib/jvm
  - java -version
  - which java
  - sudo apt install openjdk-8-jre
  - java -version
  - which java
  - sudo update-alternatives --display java
  - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - git clone -b release https://github.com/roswell/roswell.git
  - cd roswell
  - sh bootstrap
  - ./configure
  - make && sudo make install
  - ros install $LISP
  - export EXOTIC_DIR="$HOME/(some exotic name')/"
  - export EXOTIC_DIR_PYTHON="$EXOTIC_DIR/python"
  - mkdir -p "$EXOTIC_DIR"
  - rsync -rR "$HOME/build/digikar99/py4cl2" "$EXOTIC_DIR"
  - ln -s "/usr/bin/python3" "$EXOTIC_DIR_PYTHON"
  - cd ~/
  - ls -l
  - ls "$EXOTIC_DIR"
  - nproc
  - pwd
  - python3 --version
  - /"$EXOTIC_DIR_PYTHON" --version

script:
  # Testing it on the second load confirms that functionalities do not
  # solely eval-when compile-toplevel, and that they persist across multiple loads.
  - ros dynamic-space-size=8000 -e "(push :travis *features*)
            (push (print (pathname (uiop:getenv \"EXOTIC_DIR\"))) ql:*local-project-directories*)
            (print (ql:where-is-system \"py4cl2\"))
            (ql:quickload \"py4cl2/tests\")
            (setf (py4cl2:config-var 'py4cl2:pycmd)
                  (namestring (uiop:getenv \"EXOTIC_DIR_PYTHON\")))
            (py4cl2:save-config)"
  - ros dynamic-space-size=8000 -e "(in-package :cl-user)
            (push :travis *features*)
            (push (uiop:getenv \"EXOTIC_DIR\") ql:*local-project-directories*)
            (ql:quickload \"py4cl2/tests\")
            (print (py4cl2:config-var 'py4cl2:pycmd))
            (let ((report (py4cl2/tests:run)))
              (princ report)
              (when (or (plusp (slot-value report 'clunit::failed))
                        (plusp (slot-value report 'clunit::errors)))
                (uiop:quit 1)))
            (format t \"!!ALL TESTS RAN SUCCESSFULLY!!\")
            (uiop:quit 0)"
    
notifications:
  email: false
