language: common-lisp
dist: xenial

git:
  depth: 3

env:
  matrix:
    - LISP=abcl-bin
    - LISP=sbcl-bin
    - LISP=ecl
    - LISP=ccl-bin

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

install:
  - echo $PATH
  - ls /usr/local/lib/jvm/
  - sudo rm -rf /usr/local/lib/jvm
  - java -version
  - which java
  - sudo apt install openjdk-8-jre
  - java -version
  - which java
  - sudo update-alternatives --display java
  - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - git clone -b release https://github.com/roswell/roswell.git
  - cd roswell
  - sh bootstrap
  - ./configure
  - make && sudo make install
  - ros install $LISP
  - cd ~/
  - ls -l
  - nproc
  - pwd

script:
  # Testing it on the second load confirms that functionalities do not
  # solely eval-when compile-toplevel, and that they persist across multiple loads.
  - ros dynamic-space-size=8000 -e "(push :travis *features*)
            (push (uiop:getcwd) ql:*local-project-directories*)
            (ql:quickload \"py4cl2/tests\")"
  - ros dynamic-space-size=8000 -e "(in-package :cl-user)
            (push :travis *features*)
            (push (uiop:getcwd) ql:*local-project-directories*)
            (ql:quickload \"py4cl2/tests\")
            (let ((report (py4cl2/tests:run)))
              (when (or (plusp (slot-value report 'clunit::failed))
                        (plusp (slot-value report 'clunit::errors)))
                (princ report)
                (uiop:quit 1)))
            (format t \"!!ALL TESTS RAN SUCCESSFULLY!!\")
            (uiop:quit 0)"
    
notifications:
  email: false
